- name: Installing GRUB EFI package
  become: yes
  ansible.builtin.yum:
    name:
      - grub2-efi
      - shim
  notify: Update GRUB configuration

- name: Removing explicit console arguments from kernel command line
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT crashkernel=auto ci.datasource=OpenStack network-config=disabled"'
  notify: Update GRUB configuration
