- name: Configure dracut to build initrd images for generic hosts
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/dracut.conf
    search_string: hostonly=
    line: hostonly=no

- name: Installing GRUB EFI package
  become: yes
  ansible.builtin.yum:
    name:
      - grub2-efi
      - shim
  notify: Update GRUB configuration

- name: Removing explicit console arguments from kernel command line
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    search_string: GRUB_CMDLINE_LINUX=
    line: GRUB_CMDLINE_LINUX="crashkernel=auto"
  notify: Update GRUB configuration
